GET http://localhost:8000/items/foober?bool=true
content-type: application/json

###

POST http://localhost:8000/items HTTP/1.1
Content-Type: application/json

{
    "name": "uni",
    "price": 343214.3
}
