POST http://localhost:8000/api/auth/access-token HTTP/1.1
accept: application/json
Content-Type: application/x-www-form-urlencoded

grant_type=&username=nakatu&password=secret&scope=&client_id=&client_secret=

###

GET http://localhost:8000/api/auth/users/me
accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODU2NzA3NTQsInN1YiI6Im5ha2F0dSJ9.oHVE9mEZ_EVNYoaOBMwdFb1bweLmzcTUORQkcmBTM_I
